name: clean_mvp_architecture
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-102.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For service locator - use Singleton (initialize variables), then use them in main file.
  get_it: ^7.6.4

  # Data layer
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  dio: ^5.1.2
  retrofit: ^4.0.1

  # State management
  flutter_bloc: ^8.1.2
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.2
  json_serializable: ^6.6.2
  retrofit_generator: ^6.0.0+3

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
